spring:
  datasource:
    url: jdbc:sqlite:example_db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false

logging:
  level:
    com.example.library: DEBUG
